// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coredb.proto

package coredbpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// private data
type PrivateData struct {
	PriKey               []byte   `protobuf:"bytes,1,opt,name=priKey,proto3" json:"priKey,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	CreateTime           int64    `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	OnlineTime           int64    `protobuf:"varint,4,opt,name=onlineTime,proto3" json:"onlineTime,omitempty"`
	Addr                 string   `protobuf:"bytes,5,opt,name=addr,proto3" json:"addr,omitempty"`
	StrPriKey            string   `protobuf:"bytes,6,opt,name=strPriKey,proto3" json:"strPriKey,omitempty"`
	StrPubKey            string   `protobuf:"bytes,7,opt,name=strPubKey,proto3" json:"strPubKey,omitempty"`
	LstTrustNode         []string `protobuf:"bytes,8,rep,name=lstTrustNode,proto3" json:"lstTrustNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateData) Reset()         { *m = PrivateData{} }
func (m *PrivateData) String() string { return proto.CompactTextString(m) }
func (*PrivateData) ProtoMessage()    {}
func (*PrivateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_coredb_a9275488b7358ff5, []int{0}
}
func (m *PrivateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateData.Unmarshal(m, b)
}
func (m *PrivateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateData.Marshal(b, m, deterministic)
}
func (dst *PrivateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateData.Merge(dst, src)
}
func (m *PrivateData) XXX_Size() int {
	return xxx_messageInfo_PrivateData.Size(m)
}
func (m *PrivateData) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateData.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateData proto.InternalMessageInfo

func (m *PrivateData) GetPriKey() []byte {
	if m != nil {
		return m.PriKey
	}
	return nil
}

func (m *PrivateData) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *PrivateData) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *PrivateData) GetOnlineTime() int64 {
	if m != nil {
		return m.OnlineTime
	}
	return 0
}

func (m *PrivateData) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *PrivateData) GetStrPriKey() string {
	if m != nil {
		return m.StrPriKey
	}
	return ""
}

func (m *PrivateData) GetStrPubKey() string {
	if m != nil {
		return m.StrPubKey
	}
	return ""
}

func (m *PrivateData) GetLstTrustNode() []string {
	if m != nil {
		return m.LstTrustNode
	}
	return nil
}

// node info
type NodeInfo struct {
	ServAddr      string   `protobuf:"bytes,1,opt,name=servAddr,proto3" json:"servAddr,omitempty"`
	Addr          string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Name          string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ConnectNums   int32    `protobuf:"varint,4,opt,name=connectNums,proto3" json:"connectNums,omitempty"`
	ConnectedNums int32    `protobuf:"varint,5,opt,name=connectedNums,proto3" json:"connectedNums,omitempty"`
	CtrlID        int64    `protobuf:"varint,6,opt,name=ctrlID,proto3" json:"ctrlID,omitempty"`
	LstClientAddr []string `protobuf:"bytes,7,rep,name=lstClientAddr,proto3" json:"lstClientAddr,omitempty"`
	AddTime       int64    `protobuf:"varint,8,opt,name=addTime,proto3" json:"addTime,omitempty"`
	ConnectMe     bool     `protobuf:"varint,9,opt,name=connectMe,proto3" json:"connectMe,omitempty"`
	ConnectNode   bool     `protobuf:"varint,10,opt,name=connectNode,proto3" json:"connectNode,omitempty"`
	// nodetype version
	NodeTypeVersion string `protobuf:"bytes,11,opt,name=nodeTypeVersion,proto3" json:"nodeTypeVersion,omitempty"`
	// node type
	NodeType string `protobuf:"bytes,12,opt,name=nodeType,proto3" json:"nodeType,omitempty"`
	// jarviscore version
	CoreVersion string `protobuf:"bytes,13,opt,name=coreVersion,proto3" json:"coreVersion,omitempty"`
	// current message id
	// I send message for this node, the msgid is lastSendMsgID + 1
	LastSendMsgID int64 `protobuf:"varint,14,opt,name=lastSendMsgID,proto3" json:"lastSendMsgID,omitempty"`
	// last connect time
	LastConnectTime int64 `protobuf:"varint,15,opt,name=lastConnectTime,proto3" json:"lastConnectTime,omitempty"`
	// last connected time
	LastConnectedTime int64 `protobuf:"varint,16,opt,name=lastConnectedTime,proto3" json:"lastConnectedTime,omitempty"`
	// last connect me time
	LastConnectMeTime int64 `protobuf:"varint,17,opt,name=lastConnectMeTime,proto3" json:"lastConnectMeTime,omitempty"`
	// groups
	LstGroups []string `protobuf:"bytes,18,rep,name=lstGroups,proto3" json:"lstGroups,omitempty"`
	// deprecated
	Deprecated bool `protobuf:"varint,19,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// last receive message id
	LastRecvMsgID        int64    `protobuf:"varint,20,opt,name=lastRecvMsgID,proto3" json:"lastRecvMsgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_coredb_a9275488b7358ff5, []int{1}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (dst *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(dst, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetServAddr() string {
	if m != nil {
		return m.ServAddr
	}
	return ""
}

func (m *NodeInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetConnectNums() int32 {
	if m != nil {
		return m.ConnectNums
	}
	return 0
}

func (m *NodeInfo) GetConnectedNums() int32 {
	if m != nil {
		return m.ConnectedNums
	}
	return 0
}

func (m *NodeInfo) GetCtrlID() int64 {
	if m != nil {
		return m.CtrlID
	}
	return 0
}

func (m *NodeInfo) GetLstClientAddr() []string {
	if m != nil {
		return m.LstClientAddr
	}
	return nil
}

func (m *NodeInfo) GetAddTime() int64 {
	if m != nil {
		return m.AddTime
	}
	return 0
}

func (m *NodeInfo) GetConnectMe() bool {
	if m != nil {
		return m.ConnectMe
	}
	return false
}

func (m *NodeInfo) GetConnectNode() bool {
	if m != nil {
		return m.ConnectNode
	}
	return false
}

func (m *NodeInfo) GetNodeTypeVersion() string {
	if m != nil {
		return m.NodeTypeVersion
	}
	return ""
}

func (m *NodeInfo) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *NodeInfo) GetCoreVersion() string {
	if m != nil {
		return m.CoreVersion
	}
	return ""
}

func (m *NodeInfo) GetLastSendMsgID() int64 {
	if m != nil {
		return m.LastSendMsgID
	}
	return 0
}

func (m *NodeInfo) GetLastConnectTime() int64 {
	if m != nil {
		return m.LastConnectTime
	}
	return 0
}

func (m *NodeInfo) GetLastConnectedTime() int64 {
	if m != nil {
		return m.LastConnectedTime
	}
	return 0
}

func (m *NodeInfo) GetLastConnectMeTime() int64 {
	if m != nil {
		return m.LastConnectMeTime
	}
	return 0
}

func (m *NodeInfo) GetLstGroups() []string {
	if m != nil {
		return m.LstGroups
	}
	return nil
}

func (m *NodeInfo) GetDeprecated() bool {
	if m != nil {
		return m.Deprecated
	}
	return false
}

func (m *NodeInfo) GetLastRecvMsgID() int64 {
	if m != nil {
		return m.LastRecvMsgID
	}
	return 0
}

// node info list
type NodeInfoList struct {
	SnapshotID           int64       `protobuf:"varint,1,opt,name=snapshotID,proto3" json:"snapshotID,omitempty"`
	EndIndex             int32       `protobuf:"varint,2,opt,name=endIndex,proto3" json:"endIndex,omitempty"`
	MaxIndex             int32       `protobuf:"varint,3,opt,name=maxIndex,proto3" json:"maxIndex,omitempty"`
	Nodes                []*NodeInfo `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NodeInfoList) Reset()         { *m = NodeInfoList{} }
func (m *NodeInfoList) String() string { return proto.CompactTextString(m) }
func (*NodeInfoList) ProtoMessage()    {}
func (*NodeInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_coredb_a9275488b7358ff5, []int{2}
}
func (m *NodeInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfoList.Unmarshal(m, b)
}
func (m *NodeInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfoList.Marshal(b, m, deterministic)
}
func (dst *NodeInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfoList.Merge(dst, src)
}
func (m *NodeInfoList) XXX_Size() int {
	return xxx_messageInfo_NodeInfoList.Size(m)
}
func (m *NodeInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfoList proto.InternalMessageInfo

func (m *NodeInfoList) GetSnapshotID() int64 {
	if m != nil {
		return m.SnapshotID
	}
	return 0
}

func (m *NodeInfoList) GetEndIndex() int32 {
	if m != nil {
		return m.EndIndex
	}
	return 0
}

func (m *NodeInfoList) GetMaxIndex() int32 {
	if m != nil {
		return m.MaxIndex
	}
	return 0
}

func (m *NodeInfoList) GetNodes() []*NodeInfo {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*PrivateData)(nil), "coredbpb.PrivateData")
	proto.RegisterType((*NodeInfo)(nil), "coredbpb.NodeInfo")
	proto.RegisterType((*NodeInfoList)(nil), "coredbpb.NodeInfoList")
}

func init() { proto.RegisterFile("coredb.proto", fileDescriptor_coredb_a9275488b7358ff5) }

var fileDescriptor_coredb_a9275488b7358ff5 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x94, 0xdf, 0x8a, 0xdb, 0x3c,
	0x10, 0xc5, 0xf1, 0x3a, 0x4e, 0x1c, 0x25, 0xfb, 0xed, 0xb7, 0x6a, 0x29, 0xa2, 0x94, 0x62, 0x42,
	0x2f, 0x7c, 0x51, 0x72, 0xd1, 0x3e, 0x41, 0xd9, 0x40, 0x31, 0x6d, 0x96, 0x45, 0x0d, 0xbd, 0x57,
	0xac, 0x69, 0x6b, 0x70, 0x24, 0x23, 0x29, 0x61, 0xf7, 0x2d, 0xfa, 0x14, 0x7d, 0xbf, 0xbe, 0x41,
	0xd1, 0xc8, 0xff, 0x92, 0xbd, 0xf3, 0xfc, 0xce, 0x58, 0x9a, 0x73, 0x3c, 0x98, 0x2c, 0x4b, 0x6d,
	0x40, 0xee, 0xd7, 0x8d, 0xd1, 0x4e, 0xd3, 0x34, 0x54, 0xcd, 0x7e, 0xf5, 0x37, 0x22, 0x8b, 0x07,
	0x53, 0x9d, 0x84, 0x83, 0x8d, 0x70, 0x82, 0xbe, 0x22, 0xd3, 0xc6, 0x54, 0x5f, 0xe0, 0x89, 0x45,
	0x59, 0x94, 0x2f, 0x79, 0x5b, 0x21, 0x3f, 0xee, 0x3d, 0xbf, 0x6a, 0x39, 0x56, 0xf4, 0x2d, 0x21,
	0xa5, 0x01, 0xe1, 0x60, 0x57, 0x1d, 0x80, 0xc5, 0x59, 0x94, 0xc7, 0x7c, 0x44, 0xbc, 0xae, 0x55,
	0x5d, 0xa9, 0xa0, 0x4f, 0x82, 0x3e, 0x10, 0x4a, 0xc9, 0x44, 0x48, 0x69, 0x58, 0x92, 0x45, 0xf9,
	0x9c, 0xe3, 0x33, 0x7d, 0x43, 0xe6, 0xd6, 0x99, 0x87, 0x30, 0xc6, 0x14, 0x85, 0x01, 0x74, 0x6a,
	0x18, 0x66, 0x36, 0xa8, 0x61, 0x9e, 0x15, 0x59, 0xd6, 0xd6, 0xed, 0xcc, 0xd1, 0xba, 0x7b, 0x2d,
	0x81, 0xa5, 0x59, 0x9c, 0xcf, 0xf9, 0x19, 0x5b, 0xfd, 0x49, 0x48, 0xea, 0x1f, 0x0a, 0xf5, 0x43,
	0xd3, 0xd7, 0x24, 0xb5, 0x60, 0x4e, 0x9f, 0xfc, 0x10, 0x11, 0x9e, 0xd6, 0xd7, 0xfd, 0x70, 0x57,
	0xa3, 0xe1, 0x28, 0x99, 0x28, 0xd1, 0x5a, 0x9d, 0x73, 0x7c, 0xa6, 0x19, 0x59, 0x94, 0x5a, 0x29,
	0x28, 0xdd, 0xfd, 0xf1, 0x60, 0xd1, 0x65, 0xc2, 0xc7, 0x88, 0xbe, 0x23, 0xd7, 0x6d, 0x09, 0x12,
	0x7b, 0x12, 0xec, 0x39, 0x87, 0x3e, 0xe4, 0xd2, 0x99, 0xba, 0xd8, 0xa0, 0xeb, 0x98, 0xb7, 0x95,
	0x7f, 0xbb, 0xb6, 0xee, 0xae, 0xae, 0x40, 0x39, 0x1c, 0x74, 0x86, 0xae, 0xce, 0x21, 0x65, 0x64,
	0x26, 0xa4, 0xc4, 0x9c, 0x53, 0x7c, 0xbd, 0x2b, 0x7d, 0x64, 0xed, 0x45, 0x5b, 0x60, 0xf3, 0x2c,
	0xca, 0x53, 0x3e, 0x80, 0xf1, 0xf4, 0x3e, 0x31, 0x82, 0xfa, 0x18, 0xd1, 0x9c, 0xdc, 0x28, 0x2d,
	0x61, 0xf7, 0xd4, 0xc0, 0x77, 0x30, 0xb6, 0xd2, 0x8a, 0x2d, 0xd0, 0xfe, 0x25, 0xf6, 0x69, 0x76,
	0x88, 0x2d, 0x43, 0x9a, 0x5d, 0x1d, 0xee, 0x31, 0xfd, 0x09, 0xd7, 0x28, 0x8f, 0x11, 0xfa, 0x14,
	0xd6, 0x7d, 0x03, 0x25, 0xb7, 0xf6, 0x67, 0xb1, 0x61, 0xff, 0xa1, 0x8f, 0x73, 0xe8, 0xa7, 0xf1,
	0xe0, 0x2e, 0x0c, 0x88, 0x7e, 0x6f, 0xb0, 0xef, 0x12, 0xd3, 0xf7, 0xe4, 0x76, 0x84, 0x20, 0x64,
	0xf3, 0x3f, 0xf6, 0x3e, 0x17, 0x2e, 0xba, 0xb7, 0x61, 0x63, 0x6f, 0x9f, 0x75, 0x07, 0xc1, 0x67,
	0x5a, 0x5b, 0xf7, 0xd9, 0xe8, 0x63, 0x63, 0x19, 0xc5, 0xef, 0x31, 0x00, 0xbf, 0xf6, 0x12, 0x1a,
	0x03, 0xa5, 0x70, 0x20, 0xd9, 0x0b, 0x8c, 0x74, 0x44, 0x3a, 0xa7, 0x1c, 0xca, 0x53, 0x70, 0xfa,
	0x72, 0x70, 0xda, 0xc3, 0xd5, 0xef, 0x88, 0x2c, 0xbb, 0x45, 0xfd, 0x5a, 0x59, 0xe7, 0x8f, 0xb5,
	0x4a, 0x34, 0xf6, 0x97, 0x76, 0xc5, 0x06, 0xd7, 0x35, 0xe6, 0x23, 0xe2, 0xe3, 0x07, 0x25, 0x0b,
	0x25, 0xe1, 0x11, 0x97, 0x36, 0xe1, 0x7d, 0xed, 0xb5, 0x83, 0x78, 0x0c, 0x5a, 0x1c, 0xb4, 0xae,
	0xa6, 0x39, 0x49, 0xfc, 0x67, 0xf2, 0xab, 0x1b, 0xe7, 0x8b, 0x0f, 0x74, 0xdd, 0xfd, 0x1f, 0xd6,
	0xdd, 0xf5, 0x3c, 0x34, 0xec, 0xa7, 0xf8, 0x03, 0xf9, 0xf8, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x58,
	0xdd, 0x07, 0xda, 0x50, 0x04, 0x00, 0x00,
}
