// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: jarviscore2.proto

package jarviscore2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// jarvis task type
type TASKTYPE int32

const (
	// normal
	TASKTYPE_NORMAL TASKTYPE = 0
)

// Enum value maps for TASKTYPE.
var (
	TASKTYPE_name = map[int32]string{
		0: "NORMAL",
	}
	TASKTYPE_value = map[string]int32{
		"NORMAL": 0,
	}
)

func (x TASKTYPE) Enum() *TASKTYPE {
	p := new(TASKTYPE)
	*p = x
	return p
}

func (x TASKTYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TASKTYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_jarviscore2_proto_enumTypes[0].Descriptor()
}

func (TASKTYPE) Type() protoreflect.EnumType {
	return &file_jarviscore2_proto_enumTypes[0]
}

func (x TASKTYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TASKTYPE.Descriptor instead.
func (TASKTYPE) EnumDescriptor() ([]byte, []int) {
	return file_jarviscore2_proto_rawDescGZIP(), []int{0}
}

// Task
type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type TASKTYPE `protobuf:"varint,1,opt,name=type,proto3,enum=jarviscore2pb.TASKTYPE" json:"type,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jarviscore2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_jarviscore2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_jarviscore2_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetType() TASKTYPE {
	if x != nil {
		return x.Type
	}
	return TASKTYPE_NORMAL
}

var File_jarviscore2_proto protoreflect.FileDescriptor

var file_jarviscore2_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6a, 0x61, 0x72, 0x76, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6a, 0x61, 0x72, 0x76, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32,
	0x70, 0x62, 0x22, 0x33, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6a, 0x61, 0x72, 0x76, 0x69,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x70, 0x62, 0x2e, 0x54, 0x41, 0x53, 0x4b, 0x54, 0x59, 0x50,
	0x45, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x16, 0x0a, 0x08, 0x54, 0x41, 0x53, 0x4b, 0x54,
	0x59, 0x50, 0x45, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x42,
	0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68,
	0x73, 0x30, 0x30, 0x37, 0x2f, 0x6a, 0x61, 0x72, 0x76, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x76, 0x32, 0x2f, 0x6a, 0x61, 0x72, 0x76, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jarviscore2_proto_rawDescOnce sync.Once
	file_jarviscore2_proto_rawDescData = file_jarviscore2_proto_rawDesc
)

func file_jarviscore2_proto_rawDescGZIP() []byte {
	file_jarviscore2_proto_rawDescOnce.Do(func() {
		file_jarviscore2_proto_rawDescData = protoimpl.X.CompressGZIP(file_jarviscore2_proto_rawDescData)
	})
	return file_jarviscore2_proto_rawDescData
}

var file_jarviscore2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jarviscore2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jarviscore2_proto_goTypes = []interface{}{
	(TASKTYPE)(0), // 0: jarviscore2pb.TASKTYPE
	(*Task)(nil),  // 1: jarviscore2pb.Task
}
var file_jarviscore2_proto_depIdxs = []int32{
	0, // 0: jarviscore2pb.Task.type:type_name -> jarviscore2pb.TASKTYPE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jarviscore2_proto_init() }
func file_jarviscore2_proto_init() {
	if File_jarviscore2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jarviscore2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jarviscore2_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jarviscore2_proto_goTypes,
		DependencyIndexes: file_jarviscore2_proto_depIdxs,
		EnumInfos:         file_jarviscore2_proto_enumTypes,
		MessageInfos:      file_jarviscore2_proto_msgTypes,
	}.Build()
	File_jarviscore2_proto = out.File
	file_jarviscore2_proto_rawDesc = nil
	file_jarviscore2_proto_goTypes = nil
	file_jarviscore2_proto_depIdxs = nil
}
