#jarvis node config

# rootservaddr - jarvis root node address
rootservaddr: 'jarvis.heyalgo.io:7788'
# lsttrustnode - trust node list
lsttrustnode: ['1JJaKpZGhYPuVHc1EKiiHZEswPAB5SybW5']

# timerequestchild - requestchild time
#                  - default 180
timerequestchild: 180

# maxmsglength - max msg length
#                  - default 4mb
maxmsglength: 4194304

# pprof - pprof
pprof:
  baseurl: ':6061'

# taskserv - task server
taskserv:
  # bindaddr - my bind address
  bindaddr: ':7789'
  # servaddr - other node connct me
  servaddr: '127.0.0.1:7789'

# httpserv - http server
httpserv:
  # bindaddr - my bind address
  bindaddr: ':7787'
  # servaddr - other node connct me
  servaddr: '127.0.0.1:7787'  

# ankadb - ankadb config
ankadb:
  # dbpath - dbpath
  dbpath: './dat'
  # httpserv - http service address, it can be empty
  httpserv: ':8880'
  # ankadb engine
  engine: 'leveldb'

# log - log config
log:
  # logpath - log path
  logpath: './logs'
  # loglevel - log level, it can be debug, info, warn, error
  loglevel: 'debug'
  # logconsole - it can be output to console
  logconsole: true

# basenodeinfo - my node base config  
basenodeinfo:
  # nodename - my node name
  nodename: 'node001'
  # bindaddr - my bind address
  bindaddr: ':7788'
  # servaddr - other node connct me
  servaddr: '127.0.0.1:7788'

# autoupdate - enable automatic update  
autoupdate: true
# updatescript - If automatic updates are enabled, the script will run when the update was starting.  
#     There are some variables that can be used in this script.
#       - NewVersion: new version
updatescript: |
  cd ..
  rm -rf jarvissh.tar.gz
  wget https://github.com/zhs007/jarvissh/releases/download/{{.NewVersion}}/jarvissh.tar.gz
  tar zxvf jarvissh.tar.gz
  cd jarvissh
  ./jarvissh stop
  ./jarvissh start -d
