@startuml 

title New node joins Jarvis

NewNodeDB <- NewNode: Load database
NewNodeDB -> NewNode: If database is empty
NewNodeDB <- NewNode: Initial my database and generate a private key
NewNode -> JarvisRootNode: CONNECT_NODE - Connect root node
JarvisRootNode -> JarvisRootNodeDB: Update node info
NewNode <- JarvisRootNode: REPLY_CONNECT - Send my base information
NewNodeDB <- NewNode: Update root node
NewNode <- JarvisRootNode: If root not connected the newnode, then CONNECT_NODE - Connect root node
NewNode -> JarvisRootNode: REPLY_CONNECT - Send my base information
JarvisRootNode -> JarvisRootNodeDB: Update node info

@enduml