// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jarviscore.proto

package jarviscorepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CODE int32

const (
	CODE_OK                   CODE = 0
	CODE_INVALID_ADDR         CODE = 1
	CODE_ALREADY_IN           CODE = 2
	CODE_FORWARD_MSG          CODE = 3
	CODE_BROADCAST_MSG        CODE = 4
	CODE_NOCTRLMOD            CODE = 5
	CODE_CLIENT_ALREADY_START CODE = 6
)

var CODE_name = map[int32]string{
	0: "OK",
	1: "INVALID_ADDR",
	2: "ALREADY_IN",
	3: "FORWARD_MSG",
	4: "BROADCAST_MSG",
	5: "NOCTRLMOD",
	6: "CLIENT_ALREADY_START",
}
var CODE_value = map[string]int32{
	"OK":                   0,
	"INVALID_ADDR":         1,
	"ALREADY_IN":           2,
	"FORWARD_MSG":          3,
	"BROADCAST_MSG":        4,
	"NOCTRLMOD":            5,
	"CLIENT_ALREADY_START": 6,
}

func (x CODE) String() string {
	return proto.EnumName(CODE_name, int32(x))
}
func (CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{0}
}

type NODETYPE int32

const (
	NODETYPE_NORMAL  NODETYPE = 0
	NODETYPE_SH      NODETYPE = 1
	NODETYPE_TELEBOT NODETYPE = 2
)

var NODETYPE_name = map[int32]string{
	0: "NORMAL",
	1: "SH",
	2: "TELEBOT",
}
var NODETYPE_value = map[string]int32{
	"NORMAL":  0,
	"SH":      1,
	"TELEBOT": 2,
}

func (x NODETYPE) String() string {
	return proto.EnumName(NODETYPE_name, int32(x))
}
func (NODETYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{1}
}

type CHANNELTYPE int32

const (
	CHANNELTYPE_NODEINFO CHANNELTYPE = 0
	CHANNELTYPE_CTRL     CHANNELTYPE = 1
)

var CHANNELTYPE_name = map[int32]string{
	0: "NODEINFO",
	1: "CTRL",
}
var CHANNELTYPE_value = map[string]int32{
	"NODEINFO": 0,
	"CTRL":     1,
}

func (x CHANNELTYPE) String() string {
	return proto.EnumName(CHANNELTYPE_name, int32(x))
}
func (CHANNELTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{2}
}

type CTRLTYPE int32

const (
	CTRLTYPE_SHELL CTRLTYPE = 0
)

var CTRLTYPE_name = map[int32]string{
	0: "SHELL",
}
var CTRLTYPE_value = map[string]int32{
	"SHELL": 0,
}

func (x CTRLTYPE) String() string {
	return proto.EnumName(CTRLTYPE_name, int32(x))
}
func (CTRLTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{3}
}

type PrivateKey struct {
	PriKey               []byte   `protobuf:"bytes,1,opt,name=priKey,proto3" json:"priKey,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Wifc                 string   `protobuf:"bytes,3,opt,name=wifc,proto3" json:"wifc,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKey) Reset()         { *m = PrivateKey{} }
func (m *PrivateKey) String() string { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()    {}
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{0}
}
func (m *PrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKey.Unmarshal(m, b)
}
func (m *PrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKey.Marshal(b, m, deterministic)
}
func (dst *PrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKey.Merge(dst, src)
}
func (m *PrivateKey) XXX_Size() int {
	return xxx_messageInfo_PrivateKey.Size(m)
}
func (m *PrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKey proto.InternalMessageInfo

func (m *PrivateKey) GetPriKey() []byte {
	if m != nil {
		return m.PriKey
	}
	return nil
}

func (m *PrivateKey) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *PrivateKey) GetWifc() string {
	if m != nil {
		return m.Wifc
	}
	return ""
}

func (m *PrivateKey) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type PublicKey struct {
	PubKey               []byte   `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{1}
}
func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (dst *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(dst, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *PublicKey) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Join struct {
	ServAddr             string   `protobuf:"bytes,1,opt,name=servAddr,proto3" json:"servAddr,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NodeType             NODETYPE `protobuf:"varint,4,opt,name=nodeType,proto3,enum=jarviscorepb.NODETYPE" json:"nodeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Join) Reset()         { *m = Join{} }
func (m *Join) String() string { return proto.CompactTextString(m) }
func (*Join) ProtoMessage()    {}
func (*Join) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{2}
}
func (m *Join) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Join.Unmarshal(m, b)
}
func (m *Join) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Join.Marshal(b, m, deterministic)
}
func (dst *Join) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join.Merge(dst, src)
}
func (m *Join) XXX_Size() int {
	return xxx_messageInfo_Join.Size(m)
}
func (m *Join) XXX_DiscardUnknown() {
	xxx_messageInfo_Join.DiscardUnknown(m)
}

var xxx_messageInfo_Join proto.InternalMessageInfo

func (m *Join) GetServAddr() string {
	if m != nil {
		return m.ServAddr
	}
	return ""
}

func (m *Join) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Join) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Join) GetNodeType() NODETYPE {
	if m != nil {
		return m.NodeType
	}
	return NODETYPE_NORMAL
}

type ReplyJoin struct {
	Code                 CODE     `protobuf:"varint,1,opt,name=code,proto3,enum=jarviscorepb.CODE" json:"code,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NodeType             NODETYPE `protobuf:"varint,4,opt,name=nodeType,proto3,enum=jarviscorepb.NODETYPE" json:"nodeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyJoin) Reset()         { *m = ReplyJoin{} }
func (m *ReplyJoin) String() string { return proto.CompactTextString(m) }
func (*ReplyJoin) ProtoMessage()    {}
func (*ReplyJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{3}
}
func (m *ReplyJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyJoin.Unmarshal(m, b)
}
func (m *ReplyJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyJoin.Marshal(b, m, deterministic)
}
func (dst *ReplyJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyJoin.Merge(dst, src)
}
func (m *ReplyJoin) XXX_Size() int {
	return xxx_messageInfo_ReplyJoin.Size(m)
}
func (m *ReplyJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyJoin proto.InternalMessageInfo

func (m *ReplyJoin) GetCode() CODE {
	if m != nil {
		return m.Code
	}
	return CODE_OK
}

func (m *ReplyJoin) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReplyJoin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReplyJoin) GetNodeType() NODETYPE {
	if m != nil {
		return m.NodeType
	}
	return NODETYPE_NORMAL
}

type BaseReply struct {
	Code                 CODE     `protobuf:"varint,1,opt,name=code,proto3,enum=jarviscorepb.CODE" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReply) Reset()         { *m = BaseReply{} }
func (m *BaseReply) String() string { return proto.CompactTextString(m) }
func (*BaseReply) ProtoMessage()    {}
func (*BaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{4}
}
func (m *BaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReply.Unmarshal(m, b)
}
func (m *BaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReply.Marshal(b, m, deterministic)
}
func (dst *BaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReply.Merge(dst, src)
}
func (m *BaseReply) XXX_Size() int {
	return xxx_messageInfo_BaseReply.Size(m)
}
func (m *BaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReply proto.InternalMessageInfo

func (m *BaseReply) GetCode() CODE {
	if m != nil {
		return m.Code
	}
	return CODE_OK
}

type Subscribe struct {
	ChannelType          CHANNELTYPE `protobuf:"varint,1,opt,name=channelType,proto3,enum=jarviscorepb.CHANNELTYPE" json:"channelType,omitempty"`
	Addr                 string      `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Subscribe) Reset()         { *m = Subscribe{} }
func (m *Subscribe) String() string { return proto.CompactTextString(m) }
func (*Subscribe) ProtoMessage()    {}
func (*Subscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{5}
}
func (m *Subscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscribe.Unmarshal(m, b)
}
func (m *Subscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscribe.Marshal(b, m, deterministic)
}
func (dst *Subscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscribe.Merge(dst, src)
}
func (m *Subscribe) XXX_Size() int {
	return xxx_messageInfo_Subscribe.Size(m)
}
func (m *Subscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscribe.DiscardUnknown(m)
}

var xxx_messageInfo_Subscribe proto.InternalMessageInfo

func (m *Subscribe) GetChannelType() CHANNELTYPE {
	if m != nil {
		return m.ChannelType
	}
	return CHANNELTYPE_NODEINFO
}

func (m *Subscribe) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type NodeInfo struct {
	ServAddr             string   `protobuf:"bytes,1,opt,name=servAddr,proto3" json:"servAddr,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NodeType             NODETYPE `protobuf:"varint,4,opt,name=nodeType,proto3,enum=jarviscorepb.NODETYPE" json:"nodeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{6}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (dst *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(dst, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetServAddr() string {
	if m != nil {
		return m.ServAddr
	}
	return ""
}

func (m *NodeInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetNodeType() NODETYPE {
	if m != nil {
		return m.NodeType
	}
	return NODETYPE_NORMAL
}

type CtrlInfo struct {
	Ctrlid               int64    `protobuf:"varint,1,opt,name=ctrlid,proto3" json:"ctrlid,omitempty"`
	DestAddr             string   `protobuf:"bytes,2,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
	SrcAddr              string   `protobuf:"bytes,3,opt,name=srcAddr,proto3" json:"srcAddr,omitempty"`
	MyAddr               string   `protobuf:"bytes,4,opt,name=myAddr,proto3" json:"myAddr,omitempty"`
	CtrlType             CTRLTYPE `protobuf:"varint,5,opt,name=ctrlType,proto3,enum=jarviscorepb.CTRLTYPE" json:"ctrlType,omitempty"`
	Command              string   `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	ForwordNums          int32    `protobuf:"varint,7,opt,name=forwordNums,proto3" json:"forwordNums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtrlInfo) Reset()         { *m = CtrlInfo{} }
func (m *CtrlInfo) String() string { return proto.CompactTextString(m) }
func (*CtrlInfo) ProtoMessage()    {}
func (*CtrlInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{7}
}
func (m *CtrlInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtrlInfo.Unmarshal(m, b)
}
func (m *CtrlInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtrlInfo.Marshal(b, m, deterministic)
}
func (dst *CtrlInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtrlInfo.Merge(dst, src)
}
func (m *CtrlInfo) XXX_Size() int {
	return xxx_messageInfo_CtrlInfo.Size(m)
}
func (m *CtrlInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CtrlInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CtrlInfo proto.InternalMessageInfo

func (m *CtrlInfo) GetCtrlid() int64 {
	if m != nil {
		return m.Ctrlid
	}
	return 0
}

func (m *CtrlInfo) GetDestAddr() string {
	if m != nil {
		return m.DestAddr
	}
	return ""
}

func (m *CtrlInfo) GetSrcAddr() string {
	if m != nil {
		return m.SrcAddr
	}
	return ""
}

func (m *CtrlInfo) GetMyAddr() string {
	if m != nil {
		return m.MyAddr
	}
	return ""
}

func (m *CtrlInfo) GetCtrlType() CTRLTYPE {
	if m != nil {
		return m.CtrlType
	}
	return CTRLTYPE_SHELL
}

func (m *CtrlInfo) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CtrlInfo) GetForwordNums() int32 {
	if m != nil {
		return m.ForwordNums
	}
	return 0
}

type CtrlResult struct {
	Ctrlid               int64    `protobuf:"varint,1,opt,name=ctrlid,proto3" json:"ctrlid,omitempty"`
	DestAddr             string   `protobuf:"bytes,2,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
	SrcAddr              string   `protobuf:"bytes,3,opt,name=srcAddr,proto3" json:"srcAddr,omitempty"`
	MyAddr               string   `protobuf:"bytes,4,opt,name=myAddr,proto3" json:"myAddr,omitempty"`
	CtrlResult           string   `protobuf:"bytes,5,opt,name=ctrlResult,proto3" json:"ctrlResult,omitempty"`
	ForwordNums          int32    `protobuf:"varint,6,opt,name=forwordNums,proto3" json:"forwordNums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtrlResult) Reset()         { *m = CtrlResult{} }
func (m *CtrlResult) String() string { return proto.CompactTextString(m) }
func (*CtrlResult) ProtoMessage()    {}
func (*CtrlResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{8}
}
func (m *CtrlResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtrlResult.Unmarshal(m, b)
}
func (m *CtrlResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtrlResult.Marshal(b, m, deterministic)
}
func (dst *CtrlResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtrlResult.Merge(dst, src)
}
func (m *CtrlResult) XXX_Size() int {
	return xxx_messageInfo_CtrlResult.Size(m)
}
func (m *CtrlResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CtrlResult.DiscardUnknown(m)
}

var xxx_messageInfo_CtrlResult proto.InternalMessageInfo

func (m *CtrlResult) GetCtrlid() int64 {
	if m != nil {
		return m.Ctrlid
	}
	return 0
}

func (m *CtrlResult) GetDestAddr() string {
	if m != nil {
		return m.DestAddr
	}
	return ""
}

func (m *CtrlResult) GetSrcAddr() string {
	if m != nil {
		return m.SrcAddr
	}
	return ""
}

func (m *CtrlResult) GetMyAddr() string {
	if m != nil {
		return m.MyAddr
	}
	return ""
}

func (m *CtrlResult) GetCtrlResult() string {
	if m != nil {
		return m.CtrlResult
	}
	return ""
}

func (m *CtrlResult) GetForwordNums() int32 {
	if m != nil {
		return m.ForwordNums
	}
	return 0
}

type ChannelInfo struct {
	ChannelType CHANNELTYPE `protobuf:"varint,1,opt,name=channelType,proto3,enum=jarviscorepb.CHANNELTYPE" json:"channelType,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ChannelInfo_NodeInfo
	//	*ChannelInfo_CtrlInfo
	Data                 isChannelInfo_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChannelInfo) Reset()         { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()    {}
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_c3fef502999ad016, []int{9}
}
func (m *ChannelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInfo.Unmarshal(m, b)
}
func (m *ChannelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInfo.Marshal(b, m, deterministic)
}
func (dst *ChannelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInfo.Merge(dst, src)
}
func (m *ChannelInfo) XXX_Size() int {
	return xxx_messageInfo_ChannelInfo.Size(m)
}
func (m *ChannelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInfo proto.InternalMessageInfo

type isChannelInfo_Data interface {
	isChannelInfo_Data()
}

type ChannelInfo_NodeInfo struct {
	NodeInfo *NodeInfo `protobuf:"bytes,2,opt,name=nodeInfo,proto3,oneof"`
}
type ChannelInfo_CtrlInfo struct {
	CtrlInfo *CtrlInfo `protobuf:"bytes,3,opt,name=ctrlInfo,proto3,oneof"`
}

func (*ChannelInfo_NodeInfo) isChannelInfo_Data() {}
func (*ChannelInfo_CtrlInfo) isChannelInfo_Data() {}

func (m *ChannelInfo) GetData() isChannelInfo_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChannelInfo) GetChannelType() CHANNELTYPE {
	if m != nil {
		return m.ChannelType
	}
	return CHANNELTYPE_NODEINFO
}

func (m *ChannelInfo) GetNodeInfo() *NodeInfo {
	if x, ok := m.GetData().(*ChannelInfo_NodeInfo); ok {
		return x.NodeInfo
	}
	return nil
}

func (m *ChannelInfo) GetCtrlInfo() *CtrlInfo {
	if x, ok := m.GetData().(*ChannelInfo_CtrlInfo); ok {
		return x.CtrlInfo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ChannelInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ChannelInfo_OneofMarshaler, _ChannelInfo_OneofUnmarshaler, _ChannelInfo_OneofSizer, []interface{}{
		(*ChannelInfo_NodeInfo)(nil),
		(*ChannelInfo_CtrlInfo)(nil),
	}
}

func _ChannelInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ChannelInfo)
	// data
	switch x := m.Data.(type) {
	case *ChannelInfo_NodeInfo:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NodeInfo); err != nil {
			return err
		}
	case *ChannelInfo_CtrlInfo:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CtrlInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ChannelInfo.Data has unexpected type %T", x)
	}
	return nil
}

func _ChannelInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ChannelInfo)
	switch tag {
	case 2: // data.nodeInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NodeInfo)
		err := b.DecodeMessage(msg)
		m.Data = &ChannelInfo_NodeInfo{msg}
		return true, err
	case 3: // data.ctrlInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CtrlInfo)
		err := b.DecodeMessage(msg)
		m.Data = &ChannelInfo_CtrlInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ChannelInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ChannelInfo)
	// data
	switch x := m.Data.(type) {
	case *ChannelInfo_NodeInfo:
		s := proto.Size(x.NodeInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ChannelInfo_CtrlInfo:
		s := proto.Size(x.CtrlInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*PrivateKey)(nil), "jarviscorepb.PrivateKey")
	proto.RegisterType((*PublicKey)(nil), "jarviscorepb.PublicKey")
	proto.RegisterType((*Join)(nil), "jarviscorepb.Join")
	proto.RegisterType((*ReplyJoin)(nil), "jarviscorepb.ReplyJoin")
	proto.RegisterType((*BaseReply)(nil), "jarviscorepb.BaseReply")
	proto.RegisterType((*Subscribe)(nil), "jarviscorepb.Subscribe")
	proto.RegisterType((*NodeInfo)(nil), "jarviscorepb.NodeInfo")
	proto.RegisterType((*CtrlInfo)(nil), "jarviscorepb.CtrlInfo")
	proto.RegisterType((*CtrlResult)(nil), "jarviscorepb.CtrlResult")
	proto.RegisterType((*ChannelInfo)(nil), "jarviscorepb.ChannelInfo")
	proto.RegisterEnum("jarviscorepb.CODE", CODE_name, CODE_value)
	proto.RegisterEnum("jarviscorepb.NODETYPE", NODETYPE_name, NODETYPE_value)
	proto.RegisterEnum("jarviscorepb.CHANNELTYPE", CHANNELTYPE_name, CHANNELTYPE_value)
	proto.RegisterEnum("jarviscorepb.CTRLTYPE", CTRLTYPE_name, CTRLTYPE_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JarvisCoreServClient is the client API for JarvisCoreServ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JarvisCoreServClient interface {
	Join(ctx context.Context, in *Join, opts ...grpc.CallOption) (*ReplyJoin, error)
	RequestCtrl(ctx context.Context, in *CtrlInfo, opts ...grpc.CallOption) (*BaseReply, error)
	ReplyCtrl(ctx context.Context, in *CtrlResult, opts ...grpc.CallOption) (*BaseReply, error)
	Subscribe(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (JarvisCoreServ_SubscribeClient, error)
}

type jarvisCoreServClient struct {
	cc *grpc.ClientConn
}

func NewJarvisCoreServClient(cc *grpc.ClientConn) JarvisCoreServClient {
	return &jarvisCoreServClient{cc}
}

func (c *jarvisCoreServClient) Join(ctx context.Context, in *Join, opts ...grpc.CallOption) (*ReplyJoin, error) {
	out := new(ReplyJoin)
	err := c.cc.Invoke(ctx, "/jarviscorepb.JarvisCoreServ/join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jarvisCoreServClient) RequestCtrl(ctx context.Context, in *CtrlInfo, opts ...grpc.CallOption) (*BaseReply, error) {
	out := new(BaseReply)
	err := c.cc.Invoke(ctx, "/jarviscorepb.JarvisCoreServ/requestCtrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jarvisCoreServClient) ReplyCtrl(ctx context.Context, in *CtrlResult, opts ...grpc.CallOption) (*BaseReply, error) {
	out := new(BaseReply)
	err := c.cc.Invoke(ctx, "/jarviscorepb.JarvisCoreServ/replyCtrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jarvisCoreServClient) Subscribe(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (JarvisCoreServ_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JarvisCoreServ_serviceDesc.Streams[0], "/jarviscorepb.JarvisCoreServ/subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &jarvisCoreServSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JarvisCoreServ_SubscribeClient interface {
	Recv() (*ChannelInfo, error)
	grpc.ClientStream
}

type jarvisCoreServSubscribeClient struct {
	grpc.ClientStream
}

func (x *jarvisCoreServSubscribeClient) Recv() (*ChannelInfo, error) {
	m := new(ChannelInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JarvisCoreServServer is the server API for JarvisCoreServ service.
type JarvisCoreServServer interface {
	Join(context.Context, *Join) (*ReplyJoin, error)
	RequestCtrl(context.Context, *CtrlInfo) (*BaseReply, error)
	ReplyCtrl(context.Context, *CtrlResult) (*BaseReply, error)
	Subscribe(*Subscribe, JarvisCoreServ_SubscribeServer) error
}

func RegisterJarvisCoreServServer(s *grpc.Server, srv JarvisCoreServServer) {
	s.RegisterService(&_JarvisCoreServ_serviceDesc, srv)
}

func _JarvisCoreServ_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Join)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JarvisCoreServServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jarviscorepb.JarvisCoreServ/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JarvisCoreServServer).Join(ctx, req.(*Join))
	}
	return interceptor(ctx, in, info, handler)
}

func _JarvisCoreServ_RequestCtrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JarvisCoreServServer).RequestCtrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jarviscorepb.JarvisCoreServ/RequestCtrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JarvisCoreServServer).RequestCtrl(ctx, req.(*CtrlInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _JarvisCoreServ_ReplyCtrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JarvisCoreServServer).ReplyCtrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jarviscorepb.JarvisCoreServ/ReplyCtrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JarvisCoreServServer).ReplyCtrl(ctx, req.(*CtrlResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _JarvisCoreServ_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Subscribe)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JarvisCoreServServer).Subscribe(m, &jarvisCoreServSubscribeServer{stream})
}

type JarvisCoreServ_SubscribeServer interface {
	Send(*ChannelInfo) error
	grpc.ServerStream
}

type jarvisCoreServSubscribeServer struct {
	grpc.ServerStream
}

func (x *jarvisCoreServSubscribeServer) Send(m *ChannelInfo) error {
	return x.ServerStream.SendMsg(m)
}

var _JarvisCoreServ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jarviscorepb.JarvisCoreServ",
	HandlerType: (*JarvisCoreServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "join",
			Handler:    _JarvisCoreServ_Join_Handler,
		},
		{
			MethodName: "requestCtrl",
			Handler:    _JarvisCoreServ_RequestCtrl_Handler,
		},
		{
			MethodName: "replyCtrl",
			Handler:    _JarvisCoreServ_ReplyCtrl_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "subscribe",
			Handler:       _JarvisCoreServ_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jarviscore.proto",
}

func init() { proto.RegisterFile("jarviscore.proto", fileDescriptor_jarviscore_c3fef502999ad016) }

var fileDescriptor_jarviscore_c3fef502999ad016 = []byte{
	// 746 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x51, 0x6f, 0xd2, 0x50,
	0x14, 0xa6, 0xac, 0x74, 0xf4, 0x94, 0x61, 0xbd, 0xd1, 0x59, 0xf7, 0x60, 0x08, 0x89, 0x66, 0xc1,
	0x64, 0x31, 0x4c, 0xe3, 0x83, 0x2f, 0x96, 0xb6, 0x13, 0xb6, 0xae, 0x5d, 0x2e, 0x8d, 0x66, 0x89,
	0x09, 0x29, 0xed, 0x5d, 0xec, 0x02, 0x14, 0x6f, 0x0b, 0x0b, 0x0f, 0xfa, 0xe0, 0x1f, 0xd0, 0x1f,
	0xe3, 0xb3, 0xbf, 0xc5, 0x9f, 0x62, 0xee, 0x2d, 0x14, 0x06, 0xd3, 0x98, 0x18, 0xf5, 0xed, 0x9e,
	0xef, 0x9e, 0xef, 0x9c, 0xef, 0x9e, 0x7e, 0x1c, 0x40, 0xbd, 0xf4, 0xe9, 0x34, 0x4a, 0x82, 0x98,
	0x92, 0x83, 0x31, 0x8d, 0xd3, 0x18, 0x55, 0x96, 0xc8, 0xb8, 0x5f, 0x0f, 0x01, 0xce, 0x68, 0x34,
	0xf5, 0x53, 0x72, 0x42, 0x66, 0x68, 0x17, 0xa4, 0x31, 0x8d, 0x4e, 0xc8, 0x4c, 0x13, 0x6a, 0xc2,
	0x7e, 0x05, 0xcf, 0x23, 0x8e, 0x4f, 0xfa, 0x0c, 0x2f, 0xce, 0x71, 0x1e, 0x21, 0x04, 0xe2, 0x55,
	0x74, 0x11, 0x68, 0x5b, 0x35, 0x61, 0x5f, 0xc6, 0xfc, 0xcc, 0x30, 0x3f, 0x0c, 0xa9, 0x26, 0x66,
	0x18, 0x3b, 0xd7, 0x9f, 0x83, 0x7c, 0x36, 0xe9, 0x0f, 0xa2, 0xe0, 0x7a, 0x31, 0x61, 0xbd, 0x18,
	0x27, 0x16, 0x57, 0x88, 0x1f, 0x41, 0x3c, 0x8e, 0xa3, 0x11, 0xda, 0x83, 0x72, 0x42, 0xe8, 0x54,
	0x67, 0xf7, 0x02, 0xbf, 0xcf, 0xe3, 0x9b, 0x78, 0x0c, 0x1b, 0xf9, 0x43, 0xb2, 0x10, 0xc6, 0xce,
	0xa8, 0x09, 0xe5, 0x51, 0x1c, 0x12, 0x6f, 0x36, 0x26, 0x5c, 0x5c, 0xb5, 0xb9, 0x7b, 0xb0, 0x3a,
	0x8b, 0x03, 0xc7, 0x35, 0x2d, 0xef, 0xfc, 0xcc, 0xc2, 0x79, 0x5e, 0xfd, 0xb3, 0x00, 0x32, 0x26,
	0xe3, 0xc1, 0x8c, 0xab, 0x78, 0x04, 0x62, 0x10, 0x87, 0x84, 0x2b, 0xa8, 0x36, 0xd1, 0x75, 0xb6,
	0xe1, 0x9a, 0x16, 0xe6, 0xf7, 0x7f, 0x55, 0xd1, 0x21, 0xc8, 0x2d, 0x3f, 0x21, 0x5c, 0xd4, 0xef,
	0x0a, 0xaa, 0xbf, 0x05, 0xb9, 0x3b, 0xe9, 0x27, 0x01, 0x8d, 0xfa, 0x04, 0xbd, 0x00, 0x25, 0x78,
	0xe7, 0x8f, 0x46, 0x64, 0xc0, 0x1b, 0x67, 0xdc, 0xfb, 0x6b, 0xdc, 0xb6, 0xee, 0x38, 0x96, 0xcd,
	0x7b, 0xaf, 0x66, 0xdf, 0xf8, 0x91, 0x3e, 0x09, 0x50, 0x76, 0xe2, 0x90, 0x74, 0x46, 0x17, 0xf1,
	0x7f, 0xfb, 0x52, 0xdf, 0x05, 0x28, 0x1b, 0x29, 0x1d, 0x70, 0x11, 0xbb, 0x20, 0x05, 0x29, 0x1d,
	0x44, 0x21, 0x97, 0xb0, 0x85, 0xe7, 0x11, 0x13, 0x17, 0x92, 0x24, 0xd5, 0x97, 0x22, 0xf2, 0x18,
	0x69, 0xb0, 0x9d, 0xd0, 0x80, 0x5f, 0x65, 0x5a, 0x16, 0x21, 0xab, 0x36, 0x9c, 0xe9, 0x4b, 0x4f,
	0xcf, 0x23, 0x26, 0x93, 0xd5, 0xe5, 0x32, 0x4b, 0x37, 0xc9, 0x34, 0x3c, 0x9c, 0x8d, 0x30, 0xcf,
	0x63, 0x5d, 0x82, 0x78, 0x38, 0xf4, 0x47, 0xa1, 0x26, 0x65, 0x5d, 0xe6, 0x21, 0xaa, 0x81, 0x72,
	0x11, 0xd3, 0xab, 0x98, 0x86, 0xce, 0x64, 0x98, 0x68, 0xdb, 0x35, 0x61, 0xbf, 0x84, 0x57, 0xa1,
	0xfa, 0x57, 0x01, 0x80, 0x3d, 0x11, 0x93, 0x64, 0x32, 0x48, 0xff, 0xd1, 0x23, 0x1f, 0x00, 0x04,
	0x79, 0x4f, 0xfe, 0x4c, 0x19, 0xaf, 0x20, 0xeb, 0xb2, 0xa5, 0x4d, 0xd9, 0xdf, 0x04, 0x50, 0x8c,
	0xcc, 0x42, 0xfc, 0xe3, 0xfc, 0x91, 0xff, 0x9e, 0x66, 0xd6, 0x60, 0x85, 0xf8, 0xe3, 0x94, 0x0d,
	0x6b, 0xcc, 0x6f, 0xdb, 0x05, 0x9c, 0x67, 0x32, 0x56, 0x30, 0xf7, 0x06, 0x7f, 0xf7, 0x06, 0x6b,
	0xe1, 0x1c, 0xc6, 0x5a, 0x64, 0xb6, 0x24, 0x10, 0x43, 0x3f, 0xf5, 0x1b, 0x1f, 0x40, 0x64, 0xbf,
	0x25, 0x24, 0x41, 0xd1, 0x3d, 0x51, 0x0b, 0x48, 0x85, 0x4a, 0xc7, 0x79, 0xad, 0xdb, 0x1d, 0xb3,
	0xa7, 0x9b, 0x26, 0x56, 0x05, 0x54, 0x05, 0xd0, 0x6d, 0x6c, 0xe9, 0xe6, 0x79, 0xaf, 0xe3, 0xa8,
	0x45, 0x74, 0x0b, 0x94, 0x23, 0x17, 0xbf, 0xd1, 0xb1, 0xd9, 0x3b, 0xed, 0xbe, 0x52, 0xb7, 0xd0,
	0x6d, 0xd8, 0x69, 0x61, 0x57, 0x37, 0x0d, 0xbd, 0xeb, 0x71, 0x48, 0x44, 0x3b, 0x20, 0x3b, 0x2e,
	0x73, 0xc8, 0xa9, 0x6b, 0xaa, 0x25, 0xa4, 0xc1, 0x1d, 0xc3, 0xee, 0x58, 0x8e, 0xd7, 0x5b, 0x54,
	0xea, 0x7a, 0x3a, 0xf6, 0x54, 0xa9, 0xf1, 0x18, 0xca, 0x0b, 0xbf, 0x23, 0x00, 0xc9, 0x71, 0xf1,
	0xa9, 0x6e, 0xab, 0x05, 0x26, 0xa7, 0xdb, 0x56, 0x05, 0xa4, 0xc0, 0xb6, 0x67, 0xd9, 0x56, 0xcb,
	0xf5, 0xd4, 0x62, 0xe3, 0x21, 0x28, 0x2b, 0xb3, 0x43, 0x95, 0x8c, 0xdb, 0x71, 0x8e, 0x5c, 0xb5,
	0x80, 0xca, 0x20, 0xb2, 0x86, 0xaa, 0xd0, 0xb8, 0x0b, 0xe5, 0x85, 0x39, 0x91, 0x0c, 0xa5, 0x6e,
	0xdb, 0xb2, 0x6d, 0xb5, 0xd0, 0xfc, 0x52, 0x84, 0xea, 0x31, 0x9f, 0x8b, 0x11, 0x53, 0xd2, 0x25,
	0x74, 0x8a, 0x9e, 0x81, 0x78, 0xc9, 0x76, 0xdf, 0xda, 0x72, 0x61, 0xfb, 0x70, 0xef, 0xde, 0x75,
	0x2c, 0x5f, 0x94, 0xf5, 0x02, 0x7a, 0x09, 0x0a, 0x25, 0xef, 0x27, 0x24, 0x49, 0xd9, 0x68, 0xd1,
	0x4f, 0xc6, 0xbd, 0x5e, 0x21, 0xdf, 0x6c, 0xbc, 0x82, 0x4c, 0xd9, 0x91, 0xf3, 0xb5, 0x4d, 0x7e,
	0xe6, 0xbf, 0x5f, 0x55, 0x30, 0x40, 0x4e, 0xf2, 0xad, 0xb7, 0x96, 0x97, 0xaf, 0xc3, 0xbd, 0x75,
	0xe7, 0x2d, 0x9d, 0x5a, 0x2f, 0x3c, 0x11, 0xfa, 0x12, 0xff, 0xd7, 0x3c, 0xfc, 0x11, 0x00, 0x00,
	0xff, 0xff, 0x3e, 0x97, 0xc8, 0xfb, 0x49, 0x07, 0x00, 0x00,
}
