// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jarviscore.proto

package jarviscorepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CODE int32

const (
	CODE_OK CODE = 0
	// addr fail
	CODE_INVALID_ADDR CODE = 1
	// already in
	CODE_ALREADY_IN CODE = 2
	// forward msg
	CODE_FORWARD_MSG CODE = 3
	// broadcast msg
	CODE_BROADCAST_MSG CODE = 4
	// no ctrl module
	CODE_NOCTRLMOD CODE = 5
	// client already start
	CODE_CLIENT_ALREADY_START CODE = 6
	// verify fail
	CODE_VERIFY_FAIL CODE = 7
	// invalid public key
	CODE_INVALID_PUBLICKEY CODE = 8
	// invalid file read size
	CODE_INVALID_FILEREADSIZE CODE = 9
	// sign fail
	CODE_SIGN_FAIL CODE = 10
	// invalid code
	CODE_INVALID_CODE CODE = 11
	// leveldb iter error
	CODE_LEVELDB_ITER_ERROR CODE = 12
	// node not connect me
	CODE_NODE_NOT_CONNECTME CODE = 20
	// not connect node
	CODE_NOT_CONNECTNODE CODE = 21
	// NodeInfoInDB decode fail
	CODE_NODEINFOINDB_DECODE_FAIL CODE = 110
	// NodeInfoInDB encode fail
	CODE_NODEINFOINDB_ENCODE_FAIL CODE = 111
	// coredb open fail
	CODE_COREDB_OPEN_FAIL CODE = 120
	// coredb nodeinfo put fail
	CODE_COREDB_NODEINFO_PUT_FAIL CODE = 121
	// coredb no addr
	CODE_COREDB_NO_ADDR CODE = 122
	// encode CtrlDataInDB fail
	CODE_CTRLDATAINDB_ENCODE_FAIL CODE = 200
	// decode CtrlDataInDB fail
	CODE_CTRLDATAINDB_DECODE_FAIL CODE = 201
	// save CtrlDataInDB fail
	CODE_CTRLDB_SAVE_CTRLDATA_FAIL CODE = 202
	// ctrldb exist strlid
	CODE_CTRLDB_EXIST_CTRLID CODE = 203
	// ctrldb not exist strlid
	CODE_CTRLDB_NOT_EXIST_CTRLID CODE = 204
	// no private key
	CODE_NO_PRIVATEKEY CODE = 10000
)

var CODE_name = map[int32]string{
	0:     "OK",
	1:     "INVALID_ADDR",
	2:     "ALREADY_IN",
	3:     "FORWARD_MSG",
	4:     "BROADCAST_MSG",
	5:     "NOCTRLMOD",
	6:     "CLIENT_ALREADY_START",
	7:     "VERIFY_FAIL",
	8:     "INVALID_PUBLICKEY",
	9:     "INVALID_FILEREADSIZE",
	10:    "SIGN_FAIL",
	11:    "INVALID_CODE",
	12:    "LEVELDB_ITER_ERROR",
	20:    "NODE_NOT_CONNECTME",
	21:    "NOT_CONNECTNODE",
	110:   "NODEINFOINDB_DECODE_FAIL",
	111:   "NODEINFOINDB_ENCODE_FAIL",
	120:   "COREDB_OPEN_FAIL",
	121:   "COREDB_NODEINFO_PUT_FAIL",
	122:   "COREDB_NO_ADDR",
	200:   "CTRLDATAINDB_ENCODE_FAIL",
	201:   "CTRLDATAINDB_DECODE_FAIL",
	202:   "CTRLDB_SAVE_CTRLDATA_FAIL",
	203:   "CTRLDB_EXIST_CTRLID",
	204:   "CTRLDB_NOT_EXIST_CTRLID",
	10000: "NO_PRIVATEKEY",
}
var CODE_value = map[string]int32{
	"OK":                        0,
	"INVALID_ADDR":              1,
	"ALREADY_IN":                2,
	"FORWARD_MSG":               3,
	"BROADCAST_MSG":             4,
	"NOCTRLMOD":                 5,
	"CLIENT_ALREADY_START":      6,
	"VERIFY_FAIL":               7,
	"INVALID_PUBLICKEY":         8,
	"INVALID_FILEREADSIZE":      9,
	"SIGN_FAIL":                 10,
	"INVALID_CODE":              11,
	"LEVELDB_ITER_ERROR":        12,
	"NODE_NOT_CONNECTME":        20,
	"NOT_CONNECTNODE":           21,
	"NODEINFOINDB_DECODE_FAIL":  110,
	"NODEINFOINDB_ENCODE_FAIL":  111,
	"COREDB_OPEN_FAIL":          120,
	"COREDB_NODEINFO_PUT_FAIL":  121,
	"COREDB_NO_ADDR":            122,
	"CTRLDATAINDB_ENCODE_FAIL":  200,
	"CTRLDATAINDB_DECODE_FAIL":  201,
	"CTRLDB_SAVE_CTRLDATA_FAIL": 202,
	"CTRLDB_EXIST_CTRLID":       203,
	"CTRLDB_NOT_EXIST_CTRLID":   204,
	"NO_PRIVATEKEY":             10000,
}

func (x CODE) String() string {
	return proto.EnumName(CODE_name, int32(x))
}
func (CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{0}
}

type NODETYPE int32

const (
	NODETYPE_NORMAL  NODETYPE = 0
	NODETYPE_SH      NODETYPE = 1
	NODETYPE_TELEBOT NODETYPE = 2
)

var NODETYPE_name = map[int32]string{
	0: "NORMAL",
	1: "SH",
	2: "TELEBOT",
}
var NODETYPE_value = map[string]int32{
	"NORMAL":  0,
	"SH":      1,
	"TELEBOT": 2,
}

func (x NODETYPE) String() string {
	return proto.EnumName(NODETYPE_name, int32(x))
}
func (NODETYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{1}
}

type CHANNELTYPE int32

const (
	CHANNELTYPE_NODEINFO CHANNELTYPE = 0
	CHANNELTYPE_CTRL     CHANNELTYPE = 1
)

var CHANNELTYPE_name = map[int32]string{
	0: "NODEINFO",
	1: "CTRL",
}
var CHANNELTYPE_value = map[string]int32{
	"NODEINFO": 0,
	"CTRL":     1,
}

func (x CHANNELTYPE) String() string {
	return proto.EnumName(CHANNELTYPE_name, int32(x))
}
func (CHANNELTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{2}
}

type CTRLTYPE int32

const (
	CTRLTYPE_SHELL CTRLTYPE = 0
	CTRLTYPE_FILE  CTRLTYPE = 2
)

var CTRLTYPE_name = map[int32]string{
	0: "SHELL",
	2: "FILE",
}
var CTRLTYPE_value = map[string]int32{
	"SHELL": 0,
	"FILE":  2,
}

func (x CTRLTYPE) String() string {
	return proto.EnumName(CTRLTYPE_name, int32(x))
}
func (CTRLTYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{3}
}

type PrivateKey struct {
	PriKey               []byte   `protobuf:"bytes,1,opt,name=priKey,proto3" json:"priKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKey) Reset()         { *m = PrivateKey{} }
func (m *PrivateKey) String() string { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()    {}
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{0}
}
func (m *PrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKey.Unmarshal(m, b)
}
func (m *PrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKey.Marshal(b, m, deterministic)
}
func (dst *PrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKey.Merge(dst, src)
}
func (m *PrivateKey) XXX_Size() int {
	return xxx_messageInfo_PrivateKey.Size(m)
}
func (m *PrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKey proto.InternalMessageInfo

func (m *PrivateKey) GetPriKey() []byte {
	if m != nil {
		return m.PriKey
	}
	return nil
}

type PublicKey struct {
	PubKey               []byte   `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{1}
}
func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (dst *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(dst, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type NodeInfo struct {
	ServAddr             string   `protobuf:"bytes,1,opt,name=servAddr,proto3" json:"servAddr,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NodeType             NODETYPE `protobuf:"varint,4,opt,name=nodeType,proto3,enum=jarviscorepb.NODETYPE" json:"nodeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{2}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (dst *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(dst, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetServAddr() string {
	if m != nil {
		return m.ServAddr
	}
	return ""
}

func (m *NodeInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetNodeType() NODETYPE {
	if m != nil {
		return m.NodeType
	}
	return NODETYPE_NORMAL
}

type NodeInfoInDB struct {
	NodeInfo             *NodeInfo `protobuf:"bytes,1,opt,name=nodeInfo,proto3" json:"nodeInfo,omitempty"`
	ConnectNums          int32     `protobuf:"varint,2,opt,name=connectNums,proto3" json:"connectNums,omitempty"`
	ConnectedNums        int32     `protobuf:"varint,3,opt,name=connectedNums,proto3" json:"connectedNums,omitempty"`
	Ctrlid               int64     `protobuf:"varint,4,opt,name=ctrlid,proto3" json:"ctrlid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NodeInfoInDB) Reset()         { *m = NodeInfoInDB{} }
func (m *NodeInfoInDB) String() string { return proto.CompactTextString(m) }
func (*NodeInfoInDB) ProtoMessage()    {}
func (*NodeInfoInDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{3}
}
func (m *NodeInfoInDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfoInDB.Unmarshal(m, b)
}
func (m *NodeInfoInDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfoInDB.Marshal(b, m, deterministic)
}
func (dst *NodeInfoInDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfoInDB.Merge(dst, src)
}
func (m *NodeInfoInDB) XXX_Size() int {
	return xxx_messageInfo_NodeInfoInDB.Size(m)
}
func (m *NodeInfoInDB) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfoInDB.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfoInDB proto.InternalMessageInfo

func (m *NodeInfoInDB) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *NodeInfoInDB) GetConnectNums() int32 {
	if m != nil {
		return m.ConnectNums
	}
	return 0
}

func (m *NodeInfoInDB) GetConnectedNums() int32 {
	if m != nil {
		return m.ConnectedNums
	}
	return 0
}

func (m *NodeInfoInDB) GetCtrlid() int64 {
	if m != nil {
		return m.Ctrlid
	}
	return 0
}

type CtrlDataInDB struct {
	Ctrlid               int64    `protobuf:"varint,1,opt,name=ctrlid,proto3" json:"ctrlid,omitempty"`
	CtrlType             CTRLTYPE `protobuf:"varint,2,opt,name=ctrlType,proto3,enum=jarviscorepb.CTRLTYPE" json:"ctrlType,omitempty"`
	ForwordAddr          string   `protobuf:"bytes,3,opt,name=forwordAddr,proto3" json:"forwordAddr,omitempty"`
	Command              []byte   `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Result               []byte   `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	ForwordNums          int32    `protobuf:"varint,6,opt,name=forwordNums,proto3" json:"forwordNums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtrlDataInDB) Reset()         { *m = CtrlDataInDB{} }
func (m *CtrlDataInDB) String() string { return proto.CompactTextString(m) }
func (*CtrlDataInDB) ProtoMessage()    {}
func (*CtrlDataInDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{4}
}
func (m *CtrlDataInDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtrlDataInDB.Unmarshal(m, b)
}
func (m *CtrlDataInDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtrlDataInDB.Marshal(b, m, deterministic)
}
func (dst *CtrlDataInDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtrlDataInDB.Merge(dst, src)
}
func (m *CtrlDataInDB) XXX_Size() int {
	return xxx_messageInfo_CtrlDataInDB.Size(m)
}
func (m *CtrlDataInDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CtrlDataInDB.DiscardUnknown(m)
}

var xxx_messageInfo_CtrlDataInDB proto.InternalMessageInfo

func (m *CtrlDataInDB) GetCtrlid() int64 {
	if m != nil {
		return m.Ctrlid
	}
	return 0
}

func (m *CtrlDataInDB) GetCtrlType() CTRLTYPE {
	if m != nil {
		return m.CtrlType
	}
	return CTRLTYPE_SHELL
}

func (m *CtrlDataInDB) GetForwordAddr() string {
	if m != nil {
		return m.ForwordAddr
	}
	return ""
}

func (m *CtrlDataInDB) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *CtrlDataInDB) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CtrlDataInDB) GetForwordNums() int32 {
	if m != nil {
		return m.ForwordNums
	}
	return 0
}

type Join struct {
	ServAddr             string   `protobuf:"bytes,1,opt,name=servAddr,proto3" json:"servAddr,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NodeType             NODETYPE `protobuf:"varint,4,opt,name=nodeType,proto3,enum=jarviscorepb.NODETYPE" json:"nodeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Join) Reset()         { *m = Join{} }
func (m *Join) String() string { return proto.CompactTextString(m) }
func (*Join) ProtoMessage()    {}
func (*Join) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{5}
}
func (m *Join) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Join.Unmarshal(m, b)
}
func (m *Join) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Join.Marshal(b, m, deterministic)
}
func (dst *Join) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join.Merge(dst, src)
}
func (m *Join) XXX_Size() int {
	return xxx_messageInfo_Join.Size(m)
}
func (m *Join) XXX_DiscardUnknown() {
	xxx_messageInfo_Join.DiscardUnknown(m)
}

var xxx_messageInfo_Join proto.InternalMessageInfo

func (m *Join) GetServAddr() string {
	if m != nil {
		return m.ServAddr
	}
	return ""
}

func (m *Join) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Join) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Join) GetNodeType() NODETYPE {
	if m != nil {
		return m.NodeType
	}
	return NODETYPE_NORMAL
}

type ReplyJoin struct {
	Code                 CODE     `protobuf:"varint,1,opt,name=code,proto3,enum=jarviscorepb.CODE" json:"code,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NodeType             NODETYPE `protobuf:"varint,4,opt,name=nodeType,proto3,enum=jarviscorepb.NODETYPE" json:"nodeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyJoin) Reset()         { *m = ReplyJoin{} }
func (m *ReplyJoin) String() string { return proto.CompactTextString(m) }
func (*ReplyJoin) ProtoMessage()    {}
func (*ReplyJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{6}
}
func (m *ReplyJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyJoin.Unmarshal(m, b)
}
func (m *ReplyJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyJoin.Marshal(b, m, deterministic)
}
func (dst *ReplyJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyJoin.Merge(dst, src)
}
func (m *ReplyJoin) XXX_Size() int {
	return xxx_messageInfo_ReplyJoin.Size(m)
}
func (m *ReplyJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyJoin proto.InternalMessageInfo

func (m *ReplyJoin) GetCode() CODE {
	if m != nil {
		return m.Code
	}
	return CODE_OK
}

func (m *ReplyJoin) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReplyJoin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReplyJoin) GetNodeType() NODETYPE {
	if m != nil {
		return m.NodeType
	}
	return NODETYPE_NORMAL
}

type BaseReply struct {
	Code                 CODE     `protobuf:"varint,1,opt,name=code,proto3,enum=jarviscorepb.CODE" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseReply) Reset()         { *m = BaseReply{} }
func (m *BaseReply) String() string { return proto.CompactTextString(m) }
func (*BaseReply) ProtoMessage()    {}
func (*BaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{7}
}
func (m *BaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseReply.Unmarshal(m, b)
}
func (m *BaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseReply.Marshal(b, m, deterministic)
}
func (dst *BaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseReply.Merge(dst, src)
}
func (m *BaseReply) XXX_Size() int {
	return xxx_messageInfo_BaseReply.Size(m)
}
func (m *BaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_BaseReply proto.InternalMessageInfo

func (m *BaseReply) GetCode() CODE {
	if m != nil {
		return m.Code
	}
	return CODE_OK
}

type Subscribe struct {
	ChannelType          CHANNELTYPE `protobuf:"varint,1,opt,name=channelType,proto3,enum=jarviscorepb.CHANNELTYPE" json:"channelType,omitempty"`
	Addr                 string      `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Subscribe) Reset()         { *m = Subscribe{} }
func (m *Subscribe) String() string { return proto.CompactTextString(m) }
func (*Subscribe) ProtoMessage()    {}
func (*Subscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{8}
}
func (m *Subscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscribe.Unmarshal(m, b)
}
func (m *Subscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscribe.Marshal(b, m, deterministic)
}
func (dst *Subscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscribe.Merge(dst, src)
}
func (m *Subscribe) XXX_Size() int {
	return xxx_messageInfo_Subscribe.Size(m)
}
func (m *Subscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscribe.DiscardUnknown(m)
}

var xxx_messageInfo_Subscribe proto.InternalMessageInfo

func (m *Subscribe) GetChannelType() CHANNELTYPE {
	if m != nil {
		return m.ChannelType
	}
	return CHANNELTYPE_NODEINFO
}

func (m *Subscribe) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type CtrlInfo struct {
	Ctrlid               int64    `protobuf:"varint,1,opt,name=ctrlid,proto3" json:"ctrlid,omitempty"`
	DestAddr             string   `protobuf:"bytes,2,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
	SrcAddr              string   `protobuf:"bytes,3,opt,name=srcAddr,proto3" json:"srcAddr,omitempty"`
	MyAddr               string   `protobuf:"bytes,4,opt,name=myAddr,proto3" json:"myAddr,omitempty"`
	CtrlType             CTRLTYPE `protobuf:"varint,5,opt,name=ctrlType,proto3,enum=jarviscorepb.CTRLTYPE" json:"ctrlType,omitempty"`
	Command              []byte   `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	ForwordNums          int32    `protobuf:"varint,7,opt,name=forwordNums,proto3" json:"forwordNums,omitempty"`
	SignR                []byte   `protobuf:"bytes,8,opt,name=signR,proto3" json:"signR,omitempty"`
	SignS                []byte   `protobuf:"bytes,9,opt,name=signS,proto3" json:"signS,omitempty"`
	PubKey               []byte   `protobuf:"bytes,10,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtrlInfo) Reset()         { *m = CtrlInfo{} }
func (m *CtrlInfo) String() string { return proto.CompactTextString(m) }
func (*CtrlInfo) ProtoMessage()    {}
func (*CtrlInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{9}
}
func (m *CtrlInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtrlInfo.Unmarshal(m, b)
}
func (m *CtrlInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtrlInfo.Marshal(b, m, deterministic)
}
func (dst *CtrlInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtrlInfo.Merge(dst, src)
}
func (m *CtrlInfo) XXX_Size() int {
	return xxx_messageInfo_CtrlInfo.Size(m)
}
func (m *CtrlInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CtrlInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CtrlInfo proto.InternalMessageInfo

func (m *CtrlInfo) GetCtrlid() int64 {
	if m != nil {
		return m.Ctrlid
	}
	return 0
}

func (m *CtrlInfo) GetDestAddr() string {
	if m != nil {
		return m.DestAddr
	}
	return ""
}

func (m *CtrlInfo) GetSrcAddr() string {
	if m != nil {
		return m.SrcAddr
	}
	return ""
}

func (m *CtrlInfo) GetMyAddr() string {
	if m != nil {
		return m.MyAddr
	}
	return ""
}

func (m *CtrlInfo) GetCtrlType() CTRLTYPE {
	if m != nil {
		return m.CtrlType
	}
	return CTRLTYPE_SHELL
}

func (m *CtrlInfo) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *CtrlInfo) GetForwordNums() int32 {
	if m != nil {
		return m.ForwordNums
	}
	return 0
}

func (m *CtrlInfo) GetSignR() []byte {
	if m != nil {
		return m.SignR
	}
	return nil
}

func (m *CtrlInfo) GetSignS() []byte {
	if m != nil {
		return m.SignS
	}
	return nil
}

func (m *CtrlInfo) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type CtrlResult struct {
	Ctrlid               int64    `protobuf:"varint,1,opt,name=ctrlid,proto3" json:"ctrlid,omitempty"`
	DestAddr             string   `protobuf:"bytes,2,opt,name=destAddr,proto3" json:"destAddr,omitempty"`
	SrcAddr              string   `protobuf:"bytes,3,opt,name=srcAddr,proto3" json:"srcAddr,omitempty"`
	MyAddr               string   `protobuf:"bytes,4,opt,name=myAddr,proto3" json:"myAddr,omitempty"`
	CtrlResult           []byte   `protobuf:"bytes,5,opt,name=ctrlResult,proto3" json:"ctrlResult,omitempty"`
	ForwordNums          int32    `protobuf:"varint,6,opt,name=forwordNums,proto3" json:"forwordNums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CtrlResult) Reset()         { *m = CtrlResult{} }
func (m *CtrlResult) String() string { return proto.CompactTextString(m) }
func (*CtrlResult) ProtoMessage()    {}
func (*CtrlResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{10}
}
func (m *CtrlResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CtrlResult.Unmarshal(m, b)
}
func (m *CtrlResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CtrlResult.Marshal(b, m, deterministic)
}
func (dst *CtrlResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CtrlResult.Merge(dst, src)
}
func (m *CtrlResult) XXX_Size() int {
	return xxx_messageInfo_CtrlResult.Size(m)
}
func (m *CtrlResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CtrlResult.DiscardUnknown(m)
}

var xxx_messageInfo_CtrlResult proto.InternalMessageInfo

func (m *CtrlResult) GetCtrlid() int64 {
	if m != nil {
		return m.Ctrlid
	}
	return 0
}

func (m *CtrlResult) GetDestAddr() string {
	if m != nil {
		return m.DestAddr
	}
	return ""
}

func (m *CtrlResult) GetSrcAddr() string {
	if m != nil {
		return m.SrcAddr
	}
	return ""
}

func (m *CtrlResult) GetMyAddr() string {
	if m != nil {
		return m.MyAddr
	}
	return ""
}

func (m *CtrlResult) GetCtrlResult() []byte {
	if m != nil {
		return m.CtrlResult
	}
	return nil
}

func (m *CtrlResult) GetForwordNums() int32 {
	if m != nil {
		return m.ForwordNums
	}
	return 0
}

type ChannelInfo struct {
	ChannelType CHANNELTYPE `protobuf:"varint,1,opt,name=channelType,proto3,enum=jarviscorepb.CHANNELTYPE" json:"channelType,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*ChannelInfo_NodeInfo
	//	*ChannelInfo_CtrlInfo
	Data                 isChannelInfo_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChannelInfo) Reset()         { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()    {}
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_jarviscore_61cdd2f97189d141, []int{11}
}
func (m *ChannelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelInfo.Unmarshal(m, b)
}
func (m *ChannelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelInfo.Marshal(b, m, deterministic)
}
func (dst *ChannelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelInfo.Merge(dst, src)
}
func (m *ChannelInfo) XXX_Size() int {
	return xxx_messageInfo_ChannelInfo.Size(m)
}
func (m *ChannelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelInfo proto.InternalMessageInfo

type isChannelInfo_Data interface {
	isChannelInfo_Data()
}

type ChannelInfo_NodeInfo struct {
	NodeInfo *NodeInfo `protobuf:"bytes,2,opt,name=nodeInfo,proto3,oneof"`
}
type ChannelInfo_CtrlInfo struct {
	CtrlInfo *CtrlInfo `protobuf:"bytes,3,opt,name=ctrlInfo,proto3,oneof"`
}

func (*ChannelInfo_NodeInfo) isChannelInfo_Data() {}
func (*ChannelInfo_CtrlInfo) isChannelInfo_Data() {}

func (m *ChannelInfo) GetData() isChannelInfo_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChannelInfo) GetChannelType() CHANNELTYPE {
	if m != nil {
		return m.ChannelType
	}
	return CHANNELTYPE_NODEINFO
}

func (m *ChannelInfo) GetNodeInfo() *NodeInfo {
	if x, ok := m.GetData().(*ChannelInfo_NodeInfo); ok {
		return x.NodeInfo
	}
	return nil
}

func (m *ChannelInfo) GetCtrlInfo() *CtrlInfo {
	if x, ok := m.GetData().(*ChannelInfo_CtrlInfo); ok {
		return x.CtrlInfo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ChannelInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ChannelInfo_OneofMarshaler, _ChannelInfo_OneofUnmarshaler, _ChannelInfo_OneofSizer, []interface{}{
		(*ChannelInfo_NodeInfo)(nil),
		(*ChannelInfo_CtrlInfo)(nil),
	}
}

func _ChannelInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ChannelInfo)
	// data
	switch x := m.Data.(type) {
	case *ChannelInfo_NodeInfo:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NodeInfo); err != nil {
			return err
		}
	case *ChannelInfo_CtrlInfo:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CtrlInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ChannelInfo.Data has unexpected type %T", x)
	}
	return nil
}

func _ChannelInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ChannelInfo)
	switch tag {
	case 2: // data.nodeInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NodeInfo)
		err := b.DecodeMessage(msg)
		m.Data = &ChannelInfo_NodeInfo{msg}
		return true, err
	case 3: // data.ctrlInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CtrlInfo)
		err := b.DecodeMessage(msg)
		m.Data = &ChannelInfo_CtrlInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ChannelInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ChannelInfo)
	// data
	switch x := m.Data.(type) {
	case *ChannelInfo_NodeInfo:
		s := proto.Size(x.NodeInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ChannelInfo_CtrlInfo:
		s := proto.Size(x.CtrlInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*PrivateKey)(nil), "jarviscorepb.PrivateKey")
	proto.RegisterType((*PublicKey)(nil), "jarviscorepb.PublicKey")
	proto.RegisterType((*NodeInfo)(nil), "jarviscorepb.NodeInfo")
	proto.RegisterType((*NodeInfoInDB)(nil), "jarviscorepb.NodeInfoInDB")
	proto.RegisterType((*CtrlDataInDB)(nil), "jarviscorepb.CtrlDataInDB")
	proto.RegisterType((*Join)(nil), "jarviscorepb.Join")
	proto.RegisterType((*ReplyJoin)(nil), "jarviscorepb.ReplyJoin")
	proto.RegisterType((*BaseReply)(nil), "jarviscorepb.BaseReply")
	proto.RegisterType((*Subscribe)(nil), "jarviscorepb.Subscribe")
	proto.RegisterType((*CtrlInfo)(nil), "jarviscorepb.CtrlInfo")
	proto.RegisterType((*CtrlResult)(nil), "jarviscorepb.CtrlResult")
	proto.RegisterType((*ChannelInfo)(nil), "jarviscorepb.ChannelInfo")
	proto.RegisterEnum("jarviscorepb.CODE", CODE_name, CODE_value)
	proto.RegisterEnum("jarviscorepb.NODETYPE", NODETYPE_name, NODETYPE_value)
	proto.RegisterEnum("jarviscorepb.CHANNELTYPE", CHANNELTYPE_name, CHANNELTYPE_value)
	proto.RegisterEnum("jarviscorepb.CTRLTYPE", CTRLTYPE_name, CTRLTYPE_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JarvisCoreServClient is the client API for JarvisCoreServ service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JarvisCoreServClient interface {
	Join(ctx context.Context, in *Join, opts ...grpc.CallOption) (*ReplyJoin, error)
	RequestCtrl(ctx context.Context, in *CtrlInfo, opts ...grpc.CallOption) (*BaseReply, error)
	ReplyCtrl(ctx context.Context, in *CtrlResult, opts ...grpc.CallOption) (*BaseReply, error)
	Subscribe(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (JarvisCoreServ_SubscribeClient, error)
}

type jarvisCoreServClient struct {
	cc *grpc.ClientConn
}

func NewJarvisCoreServClient(cc *grpc.ClientConn) JarvisCoreServClient {
	return &jarvisCoreServClient{cc}
}

func (c *jarvisCoreServClient) Join(ctx context.Context, in *Join, opts ...grpc.CallOption) (*ReplyJoin, error) {
	out := new(ReplyJoin)
	err := c.cc.Invoke(ctx, "/jarviscorepb.JarvisCoreServ/join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jarvisCoreServClient) RequestCtrl(ctx context.Context, in *CtrlInfo, opts ...grpc.CallOption) (*BaseReply, error) {
	out := new(BaseReply)
	err := c.cc.Invoke(ctx, "/jarviscorepb.JarvisCoreServ/requestCtrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jarvisCoreServClient) ReplyCtrl(ctx context.Context, in *CtrlResult, opts ...grpc.CallOption) (*BaseReply, error) {
	out := new(BaseReply)
	err := c.cc.Invoke(ctx, "/jarviscorepb.JarvisCoreServ/replyCtrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jarvisCoreServClient) Subscribe(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (JarvisCoreServ_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JarvisCoreServ_serviceDesc.Streams[0], "/jarviscorepb.JarvisCoreServ/subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &jarvisCoreServSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JarvisCoreServ_SubscribeClient interface {
	Recv() (*ChannelInfo, error)
	grpc.ClientStream
}

type jarvisCoreServSubscribeClient struct {
	grpc.ClientStream
}

func (x *jarvisCoreServSubscribeClient) Recv() (*ChannelInfo, error) {
	m := new(ChannelInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JarvisCoreServServer is the server API for JarvisCoreServ service.
type JarvisCoreServServer interface {
	Join(context.Context, *Join) (*ReplyJoin, error)
	RequestCtrl(context.Context, *CtrlInfo) (*BaseReply, error)
	ReplyCtrl(context.Context, *CtrlResult) (*BaseReply, error)
	Subscribe(*Subscribe, JarvisCoreServ_SubscribeServer) error
}

func RegisterJarvisCoreServServer(s *grpc.Server, srv JarvisCoreServServer) {
	s.RegisterService(&_JarvisCoreServ_serviceDesc, srv)
}

func _JarvisCoreServ_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Join)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JarvisCoreServServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jarviscorepb.JarvisCoreServ/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JarvisCoreServServer).Join(ctx, req.(*Join))
	}
	return interceptor(ctx, in, info, handler)
}

func _JarvisCoreServ_RequestCtrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JarvisCoreServServer).RequestCtrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jarviscorepb.JarvisCoreServ/RequestCtrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JarvisCoreServServer).RequestCtrl(ctx, req.(*CtrlInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _JarvisCoreServ_ReplyCtrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CtrlResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JarvisCoreServServer).ReplyCtrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jarviscorepb.JarvisCoreServ/ReplyCtrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JarvisCoreServServer).ReplyCtrl(ctx, req.(*CtrlResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _JarvisCoreServ_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Subscribe)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JarvisCoreServServer).Subscribe(m, &jarvisCoreServSubscribeServer{stream})
}

type JarvisCoreServ_SubscribeServer interface {
	Send(*ChannelInfo) error
	grpc.ServerStream
}

type jarvisCoreServSubscribeServer struct {
	grpc.ServerStream
}

func (x *jarvisCoreServSubscribeServer) Send(m *ChannelInfo) error {
	return x.ServerStream.SendMsg(m)
}

var _JarvisCoreServ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jarviscorepb.JarvisCoreServ",
	HandlerType: (*JarvisCoreServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "join",
			Handler:    _JarvisCoreServ_Join_Handler,
		},
		{
			MethodName: "requestCtrl",
			Handler:    _JarvisCoreServ_RequestCtrl_Handler,
		},
		{
			MethodName: "replyCtrl",
			Handler:    _JarvisCoreServ_ReplyCtrl_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "subscribe",
			Handler:       _JarvisCoreServ_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jarviscore.proto",
}

func init() { proto.RegisterFile("jarviscore.proto", fileDescriptor_jarviscore_61cdd2f97189d141) }

var fileDescriptor_jarviscore_61cdd2f97189d141 = []byte{
	// 1085 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x8e, 0x53, 0x27, 0x8d, 0x4f, 0xd2, 0xee, 0xec, 0x6c, 0xb7, 0xeb, 0xad, 0x96, 0xa5, 0x0a,
	0x0b, 0x5a, 0x15, 0xa9, 0x42, 0xdd, 0xe5, 0x8a, 0x1b, 0x1c, 0x7b, 0xba, 0xf5, 0xd6, 0xb5, 0xa3,
	0xb1, 0xb7, 0x50, 0x84, 0x64, 0x39, 0xce, 0x2c, 0x64, 0xd5, 0xda, 0xc1, 0x4e, 0x0a, 0xe1, 0x82,
	0x0b, 0x5e, 0x80, 0x7d, 0x06, 0xc4, 0x23, 0x70, 0xcd, 0x35, 0x7f, 0x17, 0x48, 0xbc, 0x10, 0x9a,
	0x99, 0x38, 0x71, 0x92, 0xee, 0xaa, 0x12, 0x82, 0xbd, 0x9b, 0xf3, 0x9d, 0x9f, 0xf9, 0x7c, 0xe6,
	0x9b, 0x33, 0x06, 0xf4, 0x22, 0xca, 0x2e, 0x07, 0x79, 0x9c, 0x66, 0x6c, 0x7f, 0x98, 0xa5, 0xa3,
	0x14, 0xb7, 0xe6, 0xc8, 0xb0, 0xd7, 0x7e, 0x00, 0xd0, 0xcd, 0x06, 0x97, 0xd1, 0x88, 0x1d, 0xb3,
	0x09, 0xde, 0x86, 0xfa, 0x30, 0x1b, 0x1c, 0xb3, 0x89, 0xae, 0xec, 0x2a, 0x0f, 0x5b, 0x74, 0x6a,
	0xb5, 0xdf, 0x01, 0xad, 0x3b, 0xee, 0x9d, 0x0f, 0xe2, 0x22, 0x68, 0xdc, 0x2b, 0x07, 0x09, 0xab,
	0xfd, 0xbd, 0x02, 0x0d, 0x37, 0xed, 0x33, 0x3b, 0x79, 0x9e, 0xe2, 0x1d, 0x68, 0xe4, 0x2c, 0xbb,
	0x34, 0xfa, 0xfd, 0x4c, 0x84, 0x69, 0x74, 0x66, 0x63, 0x0c, 0x6a, 0xc4, 0xf1, 0xaa, 0xc0, 0xc5,
	0x9a, 0x63, 0x49, 0x74, 0xc1, 0xf4, 0x35, 0x89, 0xf1, 0x35, 0x3e, 0x80, 0x46, 0x92, 0xf6, 0x59,
	0x30, 0x19, 0x32, 0x5d, 0xdd, 0x55, 0x1e, 0x6e, 0x1e, 0x6c, 0xef, 0x97, 0xc9, 0xef, 0xbb, 0x9e,
	0x45, 0x82, 0xb3, 0x2e, 0xa1, 0xb3, 0xb8, 0xf6, 0x8f, 0x0a, 0xb4, 0x0a, 0x12, 0x76, 0x62, 0x75,
	0x8a, 0x22, 0xdc, 0x16, 0x44, 0x9a, 0x2b, 0x45, 0xa6, 0x5e, 0x3a, 0x8b, 0xc3, 0xbb, 0xd0, 0x8c,
	0xd3, 0x24, 0x61, 0xf1, 0xc8, 0x1d, 0x5f, 0xe4, 0x82, 0x67, 0x8d, 0x96, 0x21, 0xfc, 0x00, 0x36,
	0xa6, 0x26, 0xeb, 0x8b, 0x98, 0x35, 0x11, 0xb3, 0x08, 0xf2, 0x4e, 0xc5, 0xa3, 0xec, 0x7c, 0xd0,
	0x17, 0xf4, 0xd7, 0xe8, 0xd4, 0x6a, 0xff, 0xa5, 0x40, 0xcb, 0x1c, 0x65, 0xe7, 0x56, 0x34, 0x8a,
	0x04, 0xc9, 0x79, 0xa0, 0x52, 0x0e, 0xe4, 0xe4, 0xf9, 0x4a, 0x74, 0xa0, 0x7a, 0x55, 0x07, 0xcc,
	0x80, 0x3a, 0xb2, 0x03, 0x45, 0x1c, 0x27, 0xff, 0x3c, 0xcd, 0xbe, 0x4e, 0xb3, 0xbe, 0x68, 0xbe,
	0x6c, 0x68, 0x19, 0xc2, 0x3a, 0xac, 0xc7, 0xe9, 0xc5, 0x45, 0x94, 0x48, 0x5e, 0x2d, 0x5a, 0x98,
	0x9c, 0x47, 0xc6, 0xf2, 0xf1, 0xf9, 0x48, 0xaf, 0xc9, 0xa3, 0x95, 0x56, 0xa9, 0xa6, 0xf8, 0xd8,
	0xba, 0x6c, 0x48, 0x09, 0x6a, 0x7f, 0x07, 0xea, 0xd3, 0x74, 0x90, 0xbc, 0xb1, 0x73, 0xff, 0x41,
	0x01, 0x8d, 0xb2, 0xe1, 0xf9, 0x44, 0xb0, 0x78, 0x0f, 0xd4, 0x38, 0xed, 0x33, 0xc1, 0x60, 0xf3,
	0x00, 0x2f, 0xf5, 0xcc, 0xb3, 0x08, 0x15, 0xfe, 0xff, 0x94, 0xd1, 0x23, 0xd0, 0x3a, 0x51, 0xce,
	0x04, 0xa9, 0xeb, 0x12, 0x6a, 0x7f, 0x0e, 0x9a, 0x3f, 0xee, 0xe5, 0x71, 0x36, 0xe8, 0x31, 0xfc,
	0x11, 0x34, 0xe3, 0x2f, 0xa3, 0x24, 0x61, 0x52, 0x00, 0x32, 0xf7, 0xee, 0x52, 0xee, 0x91, 0xe1,
	0xba, 0x44, 0x6a, 0xa0, 0x1c, 0x7d, 0xd5, 0xa7, 0xb5, 0x7f, 0xaa, 0x42, 0x83, 0xeb, 0x4e, 0x88,
	0xfc, 0x55, 0x9a, 0xdb, 0x81, 0x46, 0x9f, 0xe5, 0x23, 0x63, 0x9e, 0x3c, 0xb3, 0xb9, 0x72, 0xf2,
	0x2c, 0x2e, 0xe9, 0xaa, 0x30, 0x79, 0xb5, 0x8b, 0x89, 0x70, 0xa8, 0xc2, 0x31, 0xb5, 0x16, 0x14,
	0x5c, 0xbb, 0xa6, 0x82, 0x4b, 0xfa, 0xac, 0x2f, 0xea, 0x73, 0x49, 0x87, 0xeb, 0x2b, 0x3a, 0xc4,
	0x5b, 0x50, 0xcb, 0x07, 0x5f, 0x24, 0x54, 0x6f, 0x88, 0x4c, 0x69, 0x14, 0xa8, 0xaf, 0x6b, 0x73,
	0xd4, 0x2f, 0x0d, 0x32, 0x58, 0x18, 0x64, 0x3f, 0x2b, 0x00, 0xbc, 0x4d, 0x54, 0x8a, 0xff, 0xff,
	0x69, 0xd4, 0x7d, 0x80, 0x78, 0xb6, 0xe7, 0xf4, 0xfa, 0x95, 0x90, 0x6b, 0x5c, 0xc1, 0x5f, 0x14,
	0x68, 0x9a, 0x52, 0x01, 0xe2, 0x80, 0xff, 0x95, 0x7c, 0x1e, 0x97, 0xc6, 0x66, 0xf5, 0x75, 0x63,
	0xf3, 0xa8, 0x52, 0x1a, 0x9c, 0x8f, 0xe5, 0x69, 0x8b, 0xac, 0xb5, 0xab, 0xb2, 0x0a, 0xf5, 0xf1,
	0xac, 0x22, 0xb2, 0x53, 0x07, 0xb5, 0x1f, 0x8d, 0xa2, 0xbd, 0xbf, 0x55, 0x50, 0xf9, 0x5d, 0xc0,
	0x75, 0xa8, 0x7a, 0xc7, 0xa8, 0x82, 0x11, 0xb4, 0x6c, 0xf7, 0xd4, 0x70, 0x6c, 0x2b, 0x34, 0x2c,
	0x8b, 0x22, 0x05, 0x6f, 0x02, 0x18, 0x0e, 0x25, 0x86, 0x75, 0x16, 0xda, 0x2e, 0xaa, 0xe2, 0x1b,
	0xd0, 0x3c, 0xf4, 0xe8, 0x27, 0x06, 0xb5, 0xc2, 0x13, 0xff, 0x09, 0x5a, 0xc3, 0x37, 0x61, 0xa3,
	0x43, 0x3d, 0xc3, 0x32, 0x0d, 0x3f, 0x10, 0x90, 0x8a, 0x37, 0x40, 0x73, 0x3d, 0x2e, 0xb3, 0x13,
	0xcf, 0x42, 0x35, 0xac, 0xc3, 0x96, 0xe9, 0xd8, 0xc4, 0x0d, 0xc2, 0xa2, 0x92, 0x1f, 0x18, 0x34,
	0x40, 0x75, 0x5e, 0xec, 0x94, 0x50, 0xfb, 0xf0, 0x2c, 0x3c, 0x34, 0x6c, 0x07, 0xad, 0xe3, 0xdb,
	0x70, 0xb3, 0xd8, 0xbf, 0xfb, 0xac, 0xe3, 0xd8, 0xe6, 0x31, 0x39, 0x43, 0x0d, 0x5e, 0xa1, 0x80,
	0x0f, 0x6d, 0x87, 0xf0, 0x22, 0xbe, 0xfd, 0x19, 0x41, 0x1a, 0xdf, 0xca, 0xb7, 0x9f, 0xb8, 0x32,
	0x1f, 0xca, 0xfc, 0xf9, 0x77, 0xa1, 0x26, 0xde, 0x06, 0xec, 0x90, 0x53, 0xe2, 0x58, 0x9d, 0xd0,
	0x0e, 0x08, 0x0d, 0x09, 0xa5, 0x1e, 0x45, 0x2d, 0x8e, 0xf3, 0x11, 0x12, 0xba, 0x5e, 0x10, 0x9a,
	0x9e, 0xeb, 0x12, 0x33, 0x38, 0x21, 0x68, 0x0b, 0xdf, 0x82, 0x1b, 0x25, 0x88, 0x87, 0xa0, 0xdb,
	0xf8, 0x1e, 0xe8, 0x7c, 0x65, 0xbb, 0x87, 0x9e, 0xed, 0x5a, 0x9d, 0xd0, 0x22, 0xbc, 0xba, 0xdc,
	0x34, 0x59, 0xf1, 0x12, 0x77, 0xee, 0x4d, 0xf1, 0x16, 0x20, 0xd3, 0xa3, 0xc4, 0xea, 0x84, 0x5e,
	0x97, 0x4c, 0x89, 0x7e, 0xc3, 0x73, 0xa6, 0x68, 0x91, 0x1a, 0x76, 0x9f, 0x05, 0xd2, 0x3b, 0xc1,
	0x18, 0x36, 0x67, 0x5e, 0x79, 0x10, 0xdf, 0xe2, 0xb7, 0x40, 0xe7, 0x2d, 0xb5, 0x8c, 0xc0, 0x58,
	0xd9, 0xe5, 0x57, 0x65, 0xc5, 0x5d, 0xa6, 0xf8, 0x9b, 0x82, 0xef, 0xc3, 0x5d, 0xe1, 0xee, 0x84,
	0xbe, 0x71, 0x4a, 0xc2, 0x22, 0x54, 0xfa, 0x7f, 0x57, 0xb0, 0x0e, 0xb7, 0xa6, 0x7e, 0xf2, 0xa9,
	0xed, 0x07, 0x22, 0xc0, 0xb6, 0xd0, 0x1f, 0x0a, 0xbe, 0x07, 0x77, 0xa6, 0x1e, 0xde, 0x97, 0x05,
	0xef, 0x9f, 0x0a, 0xc6, 0xb0, 0xe1, 0x7a, 0x61, 0x97, 0xda, 0xa7, 0x46, 0x40, 0xf8, 0x61, 0xbd,
	0x74, 0xf7, 0xde, 0x87, 0x46, 0x31, 0x9d, 0x31, 0x40, 0xdd, 0xf5, 0xe8, 0x89, 0xe1, 0xa0, 0x0a,
	0x17, 0x99, 0x7f, 0x84, 0x14, 0xdc, 0x84, 0xf5, 0x80, 0x38, 0xa4, 0xe3, 0x05, 0xa8, 0xba, 0xf7,
	0x2e, 0x34, 0x4b, 0x57, 0x02, 0xb7, 0x64, 0x2e, 0x6f, 0x08, 0xaa, 0xe0, 0x06, 0xa8, 0x7c, 0x2b,
	0xa4, 0xec, 0xbd, 0x0d, 0x8d, 0x62, 0x6e, 0x61, 0x0d, 0x6a, 0xfe, 0x11, 0x71, 0x1c, 0x19, 0xc0,
	0x05, 0x81, 0xaa, 0x07, 0x2f, 0xab, 0xb0, 0xf9, 0x54, 0x08, 0xdf, 0x4c, 0x33, 0xe6, 0xb3, 0xec,
	0x12, 0x7f, 0x08, 0xea, 0x0b, 0xfe, 0x36, 0x2d, 0x0d, 0x7f, 0xfe, 0x5e, 0xed, 0xdc, 0x59, 0xc4,
	0x66, 0x0f, 0x59, 0xbb, 0x82, 0x3f, 0x86, 0x66, 0xc6, 0xbe, 0x1a, 0xb3, 0x7c, 0xc4, 0xef, 0x0e,
	0x7e, 0xc5, 0x7d, 0x5a, 0xae, 0x30, 0x7b, 0x79, 0x44, 0x05, 0x2d, 0xe3, 0x4b, 0x91, 0xaf, 0xaf,
	0xe6, 0xcb, 0x01, 0xf3, 0xba, 0x0a, 0x26, 0x68, 0xf9, 0xec, 0x55, 0x5a, 0x8a, 0x9b, 0x3d, 0x57,
	0x3b, 0xcb, 0xa3, 0x65, 0x3e, 0x8a, 0xda, 0x95, 0x0f, 0x94, 0x5e, 0x5d, 0xfc, 0x7e, 0x3e, 0xfa,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x34, 0xf5, 0x92, 0xec, 0x92, 0x0a, 0x00, 0x00,
}
